## NBA API

### Description
- Ingest data via nba_api
- reformat data
- push data to Supabase
- This notebook will is meant to explore the nba_api package and test push some data to Supabase
- Future python files will be designed to package up consistent data pulls from the api and updates to Supabase tables
- Once data is consistently landed, I will work on building some ML models and Neural Networks to add Data Science flair to the project
- Final step will be packaging it up in a simple web app to allow others to interact

### Import Packaages

In [1]:
## import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import nba_api
from nba_api.stats.endpoints import commonplayerinfo
from nba_api.stats.static import players
from nba_api.stats.library.parameters import SeasonAll
from nba_api.stats.static import teams as static_teams
from nba_api.stats.static import players as static_players
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.endpoints import leaguedashplayerstats
import time
import requests
import json
import seaborn as sns
import sys
import os
from supabase import create_client, Client
from dotenv import load_dotenv
from datetime import datetime, timedelta

load_dotenv()

True

### Test pull to grab recent ATL games

In [3]:

atl = 1610612737  # Atlanta Hawks team_id
games = leaguegamefinder.LeagueGameFinder(team_id_nullable=atl).get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612737,ATL,Atlanta Hawks,0022501210,2025-12-12,ATL @ DET,L,241,115,...,0.839,13,24,37,27,9.0,8,20,18,-27.0
1,22025,1610612737,ATL,Atlanta Hawks,0022500351,2025-12-06,ATL @ WAS,W,241,131,...,1.000,15,30,45,36,13.0,4,12,16,15.0
2,22025,1610612737,ATL,Atlanta Hawks,0022500340,2025-12-05,ATL vs. DEN,L,241,133,...,0.938,11,34,45,35,8.0,2,12,25,-1.0
3,22025,1610612737,ATL,Atlanta Hawks,0022500327,2025-12-03,ATL vs. LAC,L,241,92,...,0.786,7,31,38,20,9.0,1,16,17,-23.0
4,22025,1610612737,ATL,Atlanta Hawks,0022500309,2025-12-01,ATL @ DET,L,241,98,...,0.727,7,27,34,27,15.0,4,13,16,-1.0

In [4]:
games.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

### Lets do some broader things to get data
- first use the static databases to get team and player IDs (thesse can be dim tables)
- then lets flush out some broader functionality with usefful endpoints

#### Grab team IDs

In [5]:
# All teams (list[dict])
teams_list = static_teams.get_teams()
teams_df = pd.DataFrame(teams_list).sort_values("full_name")
teams_df["date_time_processed"] = pd.Timestamp.utcnow()
teams_df["date_time_processed"] = teams_df["date_time_processed"].astype(str)
teams_df.head()

,id,full_name,abbreviation,nickname,city,state,year_founded,date_time_processed
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949,2025-12-13 03:41:28.650441+00:00
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,2025-12-13 03:41:28.650441+00:00
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976,2025-12-13 03:41:28.650441+00:00
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988,2025-12-13 03:41:28.650441+00:00
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,2025-12-13 03:41:28.650441+00:00

In [6]:
def get_team_ids_df():
    teams_list = static_teams.get_teams()
    teams_df = pd.DataFrame(teams_list).sort_values("full_name")
    teams_df.rename(columns={'id': 'team_id'}, inplace=True)
    ## add a date time processed column
    teams_df["date_time_processed"] = pd.Timestamp.utcnow()
    teams_df["date_time_processed"] = teams_df["date_time_processed"].astype(str)
    return teams_df

In [7]:
teams_df = get_team_ids_df()
teams_df.head()

,team_id,full_name,abbreviation,nickname,city,state,year_founded,date_time_processed
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949,2025-12-13 03:41:30.169528+00:00
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,2025-12-13 03:41:30.169528+00:00
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976,2025-12-13 03:41:30.169528+00:00
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988,2025-12-13 03:41:30.169528+00:00
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,2025-12-13 03:41:30.169528+00:00

In [8]:
teams_df.shape

(30, 8)

#### Create some helper dictionaries

In [9]:
# Helper maps
TEAM_BY_ABBR = {t["abbreviation"]: t for t in teams_list}
TEAM_BY_ID   = {t["id"]: t for t in teams_list}

# Example lookups
TEAM_BY_ABBR["ATL"]["id"]         # -> 1610612737
TEAM_BY_ID[1610612737]["full_name"]  # -> "Atlanta Hawks"

'Atlanta Hawks'

In [10]:
def get_team_id():
    teams_list = static_teams.get_teams()
    TEAM_BY_ID   = {t["id"]: t for t in teams_list}
    return TEAM_BY_ID

In [11]:
team_id_dicts = get_team_id()

#### Grab Player IDs

In [55]:
# All players (current + historical)
players_list = static_players.get_players()
players_df = pd.DataFrame(players_list)
players_df.head()

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False

In [56]:
# Find by name (returns list; pick the first if unique)
static_players.find_players_by_full_name("LeBron James")

[{'id': 2544,
  'full_name': 'LeBron James',
  'first_name': 'LeBron',
  'last_name': 'James',
  'is_active': True}]

In [57]:
def get_player_df():
    players_list = static_players.get_players()
    players_df = pd.DataFrame(players_list)
    players_df.rename(columns={'id': 'player_id'}, inplace=True)
    ## add a date time processed column
    players_df["date_time_processed"] = pd.Timestamp.utcnow()
    players_df["date_time_processed"] = players_df["date_time_processed"].astype(str)
    return players_df

In [58]:
players_df = get_player_df()
players_df.head()

,player_id,full_name,first_name,last_name,is_active,date_time_processed
0,76001,Alaa Abdelnaby,Alaa,Abdelnaby,False,2025-12-13 04:17:53.468256+00:00
1,76002,Zaid Abdul-Aziz,Zaid,Abdul-Aziz,False,2025-12-13 04:17:53.468256+00:00
2,76003,Kareem Abdul-Jabbar,Kareem,Abdul-Jabbar,False,2025-12-13 04:17:53.468256+00:00
3,51,Mahmoud Abdul-Rauf,Mahmoud,Abdul-Rauf,False,2025-12-13 04:17:53.468256+00:00
4,1505,Tariq Abdul-Wahad,Tariq,Abdul-Wahad,False,2025-12-13 04:17:53.468256+00:00

#### Lets look at the game logs endpoint

In [20]:
## here is one call to get all atl games if you remove the date filters
## testing wht happens with same between date from and date to

atl = 1610612737  # Atlanta Hawks team_id
games = leaguegamefinder.LeagueGameFinder(team_id_nullable=atl,date_from_nullable="2025-12-06",date_to_nullable="2025-12-06").get_data_frames()[0]

games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612737,ATL,Atlanta Hawks,0022500351,2025-12-06,ATL @ WAS,W,241,131,...,1.0,15,30,45,36,13,4,12,16,15.0

In [12]:
team_id_list = [t for t in teams_df['team_id']]

In [26]:
## create logic for incremental data pull for just previous day

## get yesterday's date in yyyy-mm-dd format
yesterday = datetime.now() - timedelta(1)
yesterday_str = yesterday.strftime('%Y-%m-%d')

In [27]:
# Pull games for all teams with one call 
games_df = leaguegamefinder.LeagueGameFinder(date_from_nullable='2025-12-10',date_to_nullable=yesterday_str,timeout=90).get_data_frames()[0]
# add a date time processed column
games_df["date_time_processed"] = pd.Timestamp.utcnow()
games_df["date_time_processed"] = games_df["date_time_processed"].astype(str)

# Filter games to get only relavant teams 
team_ids = teams_df["team_id"].unique()

team_games_df = games_df[
    games_df["TEAM_ID"].isin(team_ids)
].reset_index(drop=True)

In [29]:
team_games_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,date_time_processed
0,22025,1610612758,SAC,Sacramento Kings,0022501208,2025-12-11,SAC vs. DEN,L,240,105,...,10,28,38,21,9,4,16,20,-31.0,2025-12-13 04:04:09.402258+00:00
1,22025,1610612743,DEN,Denver Nuggets,0022501208,2025-12-11,DEN @ SAC,W,241,136,...,10,36,46,35,9,0,12,18,31.0,2025-12-13 04:04:09.402258+00:00
2,22025,1610612745,HOU,Houston Rockets,0022501205,2025-12-11,HOU vs. LAC,W,240,115,...,22,29,51,26,9,1,18,22,2.0,2025-12-13 04:04:09.402258+00:00
3,22025,1610612757,POR,Portland Trail Blazers,0022501207,2025-12-11,POR @ NOP,L,242,120,...,13,28,41,27,5,7,15,19,-23.0,2025-12-13 04:04:09.402258+00:00
4,22025,1610612746,LAC,LA Clippers,0022501205,2025-12-11,LAC @ HOU,L,240,113,...,8,20,28,25,15,5,15,20,-2.0,2025-12-13 04:04:09.402258+00:00
5,22025,1610612740,NOP,New Orleans Pelicans,0022501207,2025-12-11,NOP vs. POR,W,239,143,...,19,38,57,36,10,8,8,16,23.0,2025-12-13 04:04:09.402258+00:00
6,22025,1610612749,MIL,Milwaukee Bucks,0022501206,2025-12-11,MIL vs. BOS,W,241,116,...,5,35,40,28,5,5,15,24,15.0,2025-12-13 04:04:09.402258+00:00
7,22025,1610612738,BOS,Boston Celtics,0022501206,2025-12-11,BOS @ MIL,L,239,101,...,13,26,39,18,7,1,13,15,-15.0,2025-12-13 04:04:09.402258+00:00
8,22025,1610612759,SAS,San Antonio Spurs,0022501204,2025-12-10,SAS @ LAL,W,240,132,...,9,41,50,25,9,3,10,19,13.0,2025-12-13 04:04:09.402258+00:00
9,22025,1610612756,PHX,Phoenix Suns,0022501203,2025-12-10,PHX @ OKC,L,240,89,...,7,30,37,24,12,2,20,13,-49.0,2025-12-13 04:04:09.402258+00:00
10,22025,1610612760,OKC,Oklahoma City Thunder,0022501203,2025-12-10,OKC vs. PHX,W,242,138,...,6,37,43,32,14,7,14,14,49.0,2025-12-13 04:04:09.402258+00:00
11,22025,1610612747,LAL,Los Angeles Lakers,0022501204,2025-12-10,LAL vs. SAS,L,240,119,...,6,37,43,27,4,7,11,23,-13.0,2025-12-13 04:04:09.402258+00:00

#### Make sure we got all the data

In [30]:
team_games_df['GAME_DATE'].value_counts()

GAME_DATE
2025-12-11    8
2025-12-10    4
Name: count, dtype: int64

In [31]:
## check we got yesterdays data
team_games_df[team_games_df['GAME_DATE'] == yesterday_str]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,date_time_processed
0,22025,1610612758,SAC,Sacramento Kings,0022501208,2025-12-11,SAC vs. DEN,L,240,105,...,10,28,38,21,9,4,16,20,-31.0,2025-12-13 04:04:09.402258+00:00
1,22025,1610612743,DEN,Denver Nuggets,0022501208,2025-12-11,DEN @ SAC,W,241,136,...,10,36,46,35,9,0,12,18,31.0,2025-12-13 04:04:09.402258+00:00
2,22025,1610612745,HOU,Houston Rockets,0022501205,2025-12-11,HOU vs. LAC,W,240,115,...,22,29,51,26,9,1,18,22,2.0,2025-12-13 04:04:09.402258+00:00
3,22025,1610612757,POR,Portland Trail Blazers,0022501207,2025-12-11,POR @ NOP,L,242,120,...,13,28,41,27,5,7,15,19,-23.0,2025-12-13 04:04:09.402258+00:00
4,22025,1610612746,LAC,LA Clippers,0022501205,2025-12-11,LAC @ HOU,L,240,113,...,8,20,28,25,15,5,15,20,-2.0,2025-12-13 04:04:09.402258+00:00
5,22025,1610612740,NOP,New Orleans Pelicans,0022501207,2025-12-11,NOP vs. POR,W,239,143,...,19,38,57,36,10,8,8,16,23.0,2025-12-13 04:04:09.402258+00:00
6,22025,1610612749,MIL,Milwaukee Bucks,0022501206,2025-12-11,MIL vs. BOS,W,241,116,...,5,35,40,28,5,5,15,24,15.0,2025-12-13 04:04:09.402258+00:00
7,22025,1610612738,BOS,Boston Celtics,0022501206,2025-12-11,BOS @ MIL,L,239,101,...,13,26,39,18,7,1,13,15,-15.0,2025-12-13 04:04:09.402258+00:00

In [32]:
team_games_df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS',
       'date_time_processed'],
      dtype='object')

In [33]:
# Step 1: rename columns to match Supabase schema
fact_team_games_df = team_games_df.rename(columns={
    "SEASON_ID": "season_id",
    "TEAM_ID": "team_id",
    "GAME_ID": "game_id",
    "GAME_DATE": "game_date",
    "MATCHUP": "matchup",
    "WL": "wl",
    "PTS": "pts",
    "FG_PCT": "fg_pct",
    "FG3_PCT": "fg3_pct",
    "FT_PCT": "ft_pct",
    "REB": "reb",
    "AST": "ast",
    "STL": "stl",
    "BLK": "blk",
    "TOV": "tov",
    "PLUS_MINUS": "plus_minus",
    "DATE_TIME_PROCESSED": "date_time_processed"
})

# Step 2: define the exact column order your Supabase table uses
supabase_col_order = [
    "game_id",
    "team_id",
    "game_date",
    "matchup",
    "wl",
    "pts",
    "plus_minus",
    "season_id",
    "fg_pct",
    "fg3_pct",
    "ft_pct",
    "reb",
    "ast",
    "stl",
    "blk",
    "tov",
    "date_time_processed"
]

# Step 3: restrict to those columns and reorder
fact_team_games_df = fact_team_games_df[supabase_col_order]

# Step 4: convert dates to ISO format (Supabase/Postgres friendly)
fact_team_games_df["game_date"] = (
    fact_team_games_df["game_date"].astype("datetime64[ns]").dt.date
)

fact_team_games_df.head()

,game_id,team_id,game_date,matchup,wl,pts,plus_minus,season_id,fg_pct,fg3_pct,ft_pct,reb,ast,stl,blk,tov,date_time_processed
0,0022501208,1610612758,2025-12-11,SAC vs. DEN,L,105,-31.0,22025,0.448,0.289,0.696,38,21,9,4,16,2025-12-13 04:04:09.402258+00:00
1,0022501208,1610612743,2025-12-11,DEN @ SAC,W,136,31.0,22025,0.591,0.414,0.690,46,35,9,0,12,2025-12-13 04:04:09.402258+00:00
2,0022501205,1610612745,2025-12-11,HOU vs. LAC,W,115,2.0,22025,0.462,0.353,0.810,51,26,9,1,18,2025-12-13 04:04:09.402258+00:00
3,0022501207,1610612757,2025-12-11,POR @ NOP,L,120,-23.0,22025,0.441,0.292,0.727,41,27,5,7,15,2025-12-13 04:04:09.402258+00:00
4,0022501205,1610612746,2025-12-11,LAC @ HOU,L,113,-2.0,22025,0.500,0.368,0.808,28,25,15,5,15,2025-12-13 04:04:09.402258+00:00

In [34]:
# Ensure game_date is a datetime type
fact_team_games_df["game_date"] = pd.to_datetime(fact_team_games_df["game_date"]).dt.date

# Define cutoff
# cutoff_date = pd.to_datetime("2025-12-03").date()

# Filter rows
# fact_team_games_df = fact_team_games_df[fact_team_games_df["game_date"] < cutoff_date]

fact_team_games_df.head()

,game_id,team_id,game_date,matchup,wl,pts,plus_minus,season_id,fg_pct,fg3_pct,ft_pct,reb,ast,stl,blk,tov,date_time_processed
0,0022501208,1610612758,2025-12-11,SAC vs. DEN,L,105,-31.0,22025,0.448,0.289,0.696,38,21,9,4,16,2025-12-13 04:04:09.402258+00:00
1,0022501208,1610612743,2025-12-11,DEN @ SAC,W,136,31.0,22025,0.591,0.414,0.690,46,35,9,0,12,2025-12-13 04:04:09.402258+00:00
2,0022501205,1610612745,2025-12-11,HOU vs. LAC,W,115,2.0,22025,0.462,0.353,0.810,51,26,9,1,18,2025-12-13 04:04:09.402258+00:00
3,0022501207,1610612757,2025-12-11,POR @ NOP,L,120,-23.0,22025,0.441,0.292,0.727,41,27,5,7,15,2025-12-13 04:04:09.402258+00:00
4,0022501205,1610612746,2025-12-11,LAC @ HOU,L,113,-2.0,22025,0.500,0.368,0.808,28,25,15,5,15,2025-12-13 04:04:09.402258+00:00

In [35]:
# 1) Ensure datetime, then convert to ISO string
fact_team_games_df["game_date"] = (
    pd.to_datetime(fact_team_games_df["game_date"])
      .dt.strftime("%Y-%m-%d")   # now plain strings like "2025-11-12"
)

# 2) (Recommended) Replace NaN/NaT with None so JSON can handle them
fact_team_games_df = fact_team_games_df.replace({np.nan: None})

In [36]:
## drop duplicates in the raw data
fact_team_games_df = fact_team_games_df.drop_duplicates(
    subset=["game_id", "team_id"],
    keep="first"
).reset_index(drop=True)

In [37]:
fact_team_games_df.shape

(12, 17)

#### Grab player season stats

In [44]:

SEASONS = ["2020-21","2021-22","2022-23","2023-24", "2024-25"]
player_season_dfs = []

for SEASON in SEASONS:
    print(f"Processing season: {SEASON}")
    player_season_df = leaguedashplayerstats.LeagueDashPlayerStats(
        season=SEASON,
        season_type_all_star="Regular Season",   # or "Playoffs"
        per_mode_detailed="PerGame",            # "Totals", "Per36", "Per100Possessions", etc.
        measure_type_detailed_defense="Base",       # "Base", "Advanced", "Misc", "Scoring", etc.
    ).get_data_frames()[0]
    print(f"Season {SEASON} data shape: {player_season_df.shape}")
    player_season_df['season'] = SEASON
    # add date time processed column
    player_season_df['date_time_processed'] = pd.Timestamp.utcnow()
    player_season_df["date_time_processed"] = player_season_df["date_time_processed"].astype(str)
    
    player_season_dfs.append(player_season_df)

player_season_df_compiled = pd.concat(player_season_dfs)

player_season_df_compiled.head()
player_season_df_compiled.columns

Processing season: 2020-21
Season 2020-21 data shape: (540, 67)
Processing season: 2021-22
Season 2021-22 data shape: (605, 67)
Processing season: 2022-23
Season 2022-23 data shape: (539, 67)
Processing season: 2023-24
Season 2023-24 data shape: (572, 67)
Processing season: 2024-25
Season 2024-25 data shape: (569, 67)

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT', 'season',
       'date_time_processed'],
      dtype='object')

In [79]:
player_season_df_compiled.shape

(2825, 69)

In [46]:
player_season_df_compiled['season'].value_counts()

season
2021-22    605
2023-24    572
2024-25    569
2020-21    540
2022-23    539
Name: count, dtype: int64

In [80]:
player_season_df_compiled.head()

,player_id,player_name,nickname,team_id,team_abbreviation,age,gp,w,l,w_pct,...,pfd_rank,pts_rank,plus_minus_rank,nba_fantasy_pts_rank,dd2_rank,td3_rank,wnba_fantasy_pts_rank,team_count,season,date_time_processed
0,203932,Aaron Gordon,Aaron,1610612743,DEN,25.0,50,29,21,0.580,...,79,136,139,115,115,17,117,2,2020-21,2025-12-05 01:49:48.082823+00:00
1,1628988,Aaron Holiday,Aaron,1610612754,IND,24.0,66,30,36,0.455,...,283,276,228,338,178,29,328,1,2020-21,2025-12-05 01:49:48.082823+00:00
2,1630174,Aaron Nesmith,Aaron,1610612738,BOS,21.0,46,22,24,0.478,...,411,382,250,399,245,29,388,1,2020-21,2025-12-05 01:49:48.082823+00:00
3,1627846,Abdel Nader,Abdel,1610612756,PHX,27.0,24,16,8,0.667,...,216,302,143,348,245,29,347,1,2020-21,2025-12-05 01:49:48.082823+00:00
4,1629690,Adam Mokoka,Adam,1610612741,CHI,22.0,14,3,11,0.214,...,524,518,280,525,245,29,526,1,2020-21,2025-12-05 01:49:48.082823+00:00

In [47]:
for c in player_season_df_compiled.columns:
    print(f"The data type for column, {c} is {player_season_df_compiled[c].dtype}")

The data type for column, PLAYER_ID is int64
The data type for column, PLAYER_NAME is object
The data type for column, NICKNAME is object
The data type for column, TEAM_ID is int64
The data type for column, TEAM_ABBREVIATION is object
The data type for column, AGE is float64
The data type for column, GP is int64
The data type for column, W is int64
The data type for column, L is int64
The data type for column, W_PCT is float64
The data type for column, MIN is float64
The data type for column, FGM is float64
The data type for column, FGA is float64
The data type for column, FG_PCT is float64
The data type for column, FG3M is float64
The data type for column, FG3A is float64
The data type for column, FG3_PCT is float64
The data type for column, FTM is float64
The data type for column, FTA is float64
The data type for column, FT_PCT is float64
The data type for column, OREB is float64
The data type for column, DREB is float64
The data type for column, REB is float64
The data type for column, AST is float64
The data type for column, TOV is float64
The data type for column, STL is float64
The data type for column, BLK is float64
The data type for column, BLKA is float64
The data type for column, PF is float64
The data type for column, PFD is float64
The data type for column, PTS is float64
The data type for column, PLUS_MINUS is float64
The data type for column, NBA_FANTASY_PTS is float64
The data type for column, DD2 is int64
The data type for column, TD3 is int64
The data type for column, WNBA_FANTASY_PTS is float64
The data type for column, GP_RANK is int64
The data type for column, W_RANK is int64
The data type for column, L_RANK is int64
The data type for column, W_PCT_RANK is int64
The data type for column, MIN_RANK is int64
The data type for column, FGM_RANK is int64
The data type for column, FGA_RANK is int64
The data type for column, FG_PCT_RANK is int64
The data type for column, FG3M_RANK is int64
The data type for column, FG3A_RANK is int64
The data type for column, FG3_PCT_RANK is int64
The data type for column, FTM_RANK is int64
The data type for column, FTA_RANK is int64
The data type for column, FT_PCT_RANK is int64
The data type for column, OREB_RANK is int64
The data type for column, DREB_RANK is int64
The data type for column, REB_RANK is int64
The data type for column, AST_RANK is int64
The data type for column, TOV_RANK is int64
The data type for column, STL_RANK is int64
The data type for column, BLK_RANK is int64
The data type for column, BLKA_RANK is int64
The data type for column, PF_RANK is int64
The data type for column, PFD_RANK is int64
The data type for column, PTS_RANK is int64
The data type for column, PLUS_MINUS_RANK is int64
The data type for column, NBA_FANTASY_PTS_RANK is int64
The data type for column, DD2_RANK is int64
The data type for column, TD3_RANK is int64
The data type for column, WNBA_FANTASY_PTS_RANK is int64
The data type for column, TEAM_COUNT is int64
The data type for column, season is object
The data type for column, date_time_processed is object

In [48]:
player_season_df_compiled["PLAYER_NAME"] = player_season_df_compiled["PLAYER_NAME"].astype(str)
player_season_df_compiled["NICKNAME"] = player_season_df_compiled["NICKNAME"].astype(str)
player_season_df_compiled["TEAM_ABBREVIATION"] = player_season_df_compiled["TEAM_ABBREVIATION"].astype(str)

In [49]:
rename_map = {
    "PLAYER_ID": "player_id",
    "PLAYER_NAME": "player_name",
    "NICKNAME": "nickname",
    "TEAM_ID": "team_id",
    "TEAM_ABBREVIATION": "team_abbreviation",
    "AGE": "age",
    "GP": "gp",
    "W": "w",
    "L": "l",
    "W_PCT": "w_pct",
    "MIN": "min",
    "FGM": "fgm",
    "FGA": "fga",
    "FG_PCT": "fg_pct",
    "FG3M": "fg3m",
    "FG3A": "fg3a",
    "FG3_PCT": "fg3_pct",
    "FTM": "ftm",
    "FTA": "fta",
    "FT_PCT": "ft_pct",
    "OREB": "oreb",
    "DREB": "dreb",
    "REB": "reb",
    "AST": "ast",
    "TOV": "tov",
    "STL": "stl",
    "BLK": "blk",
    "BLKA": "blka",
    "PF": "pf",
    "PFD": "pfd",
    "PTS": "pts",
    "PLUS_MINUS": "plus_minus",
    "NBA_FANTASY_PTS": "nba_fantasy_pts",
    "DD2": "dd2",
    "TD3": "td3",
    "WNBA_FANTASY_PTS": "wnba_fantasy_pts",
    "GP_RANK": "gp_rank",
    "W_RANK": "w_rank",
    "L_RANK": "l_rank",
    "W_PCT_RANK": "w_pct_rank",
    "MIN_RANK": "min_rank",
    "FGM_RANK": "fgm_rank",
    "FGA_RANK": "fga_rank",
    "FG_PCT_RANK": "fg_pct_rank",
    "FG3M_RANK": "fg3m_rank",
    "FG3A_RANK": "fg3a_rank",
    "FG3_PCT_RANK": "fg3_pct_rank",
    "FTM_RANK": "ftm_rank",
    "FTA_RANK": "fta_rank",
    "FT_PCT_RANK": "ft_pct_rank",
    "OREB_RANK": "oreb_rank",
    "DREB_RANK": "dreb_rank",
    "REB_RANK": "reb_rank",
    "AST_RANK": "ast_rank",
    "TOV_RANK": "tov_rank",
    "STL_RANK": "stl_rank",
    "BLK_RANK": "blk_rank",
    "BLKA_RANK": "blka_rank",
    "PF_RANK": "pf_rank",
    "PFD_RANK": "pfd_rank",
    "PTS_RANK": "pts_rank",
    "PLUS_MINUS_RANK": "plus_minus_rank",
    "NBA_FANTASY_PTS_RANK": "nba_fantasy_pts_rank",
    "DD2_RANK": "dd2_rank",
    "TD3_RANK": "td3_rank",
    "WNBA_FANTASY_PTS_RANK": "wnba_fantasy_pts_rank",
    "TEAM_COUNT": "team_count",
    "SEASON": "season",
    "DATE_TIME_PROCESSED": "date_time_processed"
}

player_season_df_compiled = player_season_df_compiled.rename(columns=rename_map)

#### Test write to Supabase

#### Connect to Supabase

In [50]:
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_KEY")

In [51]:
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

In [52]:
def upsert_in_chunks(
    table_name,
    records,
    chunk_size=500,
    conflict_cols=None,
    schema="public",   # 👈 default schema
):
    for i in range(0, len(records), chunk_size):
        chunk = records[i:i + chunk_size]

        # Choose schema explicitly
        query = supabase.schema(schema).table(table_name)

        if conflict_cols:
            query = query.upsert(
                chunk,
                on_conflict=",".join(conflict_cols),
            )
        else:
            query = query.insert(chunk)

        query.execute()
        print(f"{schema}.{table_name}: upserted rows {i}–{i + len(chunk) - 1}")

#### Convert dataframes to json

In [53]:
dim_teams_records = teams_df.to_dict(orient="records")

In [59]:
dim_players_records = players_df.to_dict(orient="records")

In [60]:
fact_team_games_records = fact_team_games_df.to_dict(orient="records")

In [61]:
fact_player_season_records = player_season_df_compiled.to_dict(orient="records")

In [62]:
player_season_df_compiled.columns

Index(['player_id', 'player_name', 'nickname', 'team_id', 'team_abbreviation',
       'age', 'gp', 'w', 'l', 'w_pct', 'min', 'fgm', 'fga', 'fg_pct', 'fg3m',
       'fg3a', 'fg3_pct', 'ftm', 'fta', 'ft_pct', 'oreb', 'dreb', 'reb', 'ast',
       'tov', 'stl', 'blk', 'blka', 'pf', 'pfd', 'pts', 'plus_minus',
       'nba_fantasy_pts', 'dd2', 'td3', 'wnba_fantasy_pts', 'gp_rank',
       'w_rank', 'l_rank', 'w_pct_rank', 'min_rank', 'fgm_rank', 'fga_rank',
       'fg_pct_rank', 'fg3m_rank', 'fg3a_rank', 'fg3_pct_rank', 'ftm_rank',
       'fta_rank', 'ft_pct_rank', 'oreb_rank', 'dreb_rank', 'reb_rank',
       'ast_rank', 'tov_rank', 'stl_rank', 'blk_rank', 'blka_rank', 'pf_rank',
       'pfd_rank', 'pts_rank', 'plus_minus_rank', 'nba_fantasy_pts_rank',
       'dd2_rank', 'td3_rank', 'wnba_fantasy_pts_rank', 'team_count', 'season',
       'date_time_processed'],
      dtype='object')

In [63]:
# dim_teams
upsert_in_chunks("dim_teams", dim_teams_records, chunk_size=200, conflict_cols=["team_id"],schema="staging")

staging.dim_teams: upserted rows 0–29

In [64]:
# dim_players
upsert_in_chunks("dim_players", dim_players_records, chunk_size=200, conflict_cols=["player_id"],schema="staging")

staging.dim_players: upserted rows 0–199
staging.dim_players: upserted rows 200–399
staging.dim_players: upserted rows 400–599
staging.dim_players: upserted rows 600–799
staging.dim_players: upserted rows 800–999
staging.dim_players: upserted rows 1000–1199
staging.dim_players: upserted rows 1200–1399
staging.dim_players: upserted rows 1400–1599
staging.dim_players: upserted rows 1600–1799
staging.dim_players: upserted rows 1800–1999
staging.dim_players: upserted rows 2000–2199
staging.dim_players: upserted rows 2200–2399
staging.dim_players: upserted rows 2400–2599
staging.dim_players: upserted rows 2600–2799
staging.dim_players: upserted rows 2800–2999
staging.dim_players: upserted rows 3000–3199
staging.dim_players: upserted rows 3200–3399
staging.dim_players: upserted rows 3400–3599
staging.dim_players: upserted rows 3600–3799
staging.dim_players: upserted rows 3800–3999
staging.dim_players: upserted rows 4000–4199
staging.dim_players: upserted rows 4200–4399
staging.dim_players: upserted rows 4400–4599
staging.dim_players: upserted rows 4600–4799
staging.dim_players: upserted rows 4800–4999
staging.dim_players: upserted rows 5000–5102

In [43]:
# fact_team_games
upsert_in_chunks(
    "fact_team_games",
    fact_team_games_records,
    chunk_size=400,
    conflict_cols=["game_id", "team_id"],
    schema="staging"
)

staging.fact_team_games: upserted rows 0–11

In [65]:
# fact_player_season_stats
upsert_in_chunks(
    "fact_player_season_stats",
    fact_player_season_records,
    chunk_size=500,
    conflict_cols=["player_id", "season"],
    schema="staging"
)

staging.fact_player_season_stats: upserted rows 0–499
staging.fact_player_season_stats: upserted rows 500–999
staging.fact_player_season_stats: upserted rows 1000–1499
staging.fact_player_season_stats: upserted rows 1500–1999
staging.fact_player_season_stats: upserted rows 2000–2499
staging.fact_player_season_stats: upserted rows 2500–2824

In [67]:
query = supabase.schema("staging").table("fact_team_games").select("*").limit(5).execute()

In [68]:
query

APIResponse(data=[{'season_id': '22017', 'team_id': 1610612762, 'team_abbreviation': None, 'team_name': None, 'game_id': '0021700781', 'game_date': '2018-02-03', 'matchup': 'UTA @ SAS', 'wl': 'W', 'min': None, 'pts': 120, 'fgm': None, 'fga': None, 'fg_pct': 0.565, 'fg3m': None, 'fg3a': None, 'fg3_pct': 0.522, 'ftm': None, 'fta': None, 'ft_pct': 0.833, 'oreb': None, 'dreb': None, 'reb': 37.0, 'ast': 26, 'stl': 6.0, 'blk': 5, 'tov': 17, 'pf': None, 'plus_minus': 9.0, 'date_time_processed': '2025-12-05T01:47:55.280701+00:00'}, {'season_id': '22017', 'team_id': 1610612762, 'team_abbreviation': None, 'team_name': None, 'game_id': '0021700773', 'game_date': '2018-02-02', 'matchup': 'UTA @ PHX', 'wl': 'W', 'min': None, 'pts': 129, 'fgm': None, 'fga': None, 'fg_pct': 0.567, 'fg3m': None, 'fg3a': None, 'fg3_pct': 0.517, 'ftm': None, 'fta': None, 'ft_pct': 0.706, 'oreb': None, 'dreb': None, 'reb': 51.0, 'ast': 30, 'stl': 7.0, 'blk': 6, 'tov': 11, 'pf': None, 'plus_minus': 32.0, 'date_time_processed': '2025-12-05T01:47:55.280701+00:00'}, {'season_id': '22017', 'team_id': 1610612762, 'team_abbreviation': None, 'team_name': None, 'game_id': '0021700751', 'game_date': '2018-01-30', 'matchup': 'UTA vs. GSW', 'wl': 'W', 'min': None, 'pts': 129, 'fgm': None, 'fga': None, 'fg_pct': 0.582, 'fg3m': None, 'fg3a': None, 'fg3_pct': 0.5, 'ftm': None, 'fta': None, 'ft_pct': 0.643, 'oreb': None, 'dreb': None, 'reb': 42.0, 'ast': 25, 'stl': 16.0, 'blk': 3, 'tov': 11, 'pf': None, 'plus_minus': 30.0, 'date_time_processed': '2025-12-05T01:47:55.280701+00:00'}, {'season_id': '22017', 'team_id': 1610612762, 'team_abbreviation': None, 'team_name': None, 'game_id': '0021700716', 'game_date': '2018-01-26', 'matchup': 'UTA @ TOR', 'wl': 'W', 'min': None, 'pts': 97, 'fgm': None, 'fga': None, 'fg_pct': 0.414, 'fg3m': None, 'fg3a': None, 'fg3_pct': 0.476, 'ftm': None, 'fta': None, 'ft_pct': 0.714, 'oreb': None, 'dreb': None, 'reb': 47.0, 'ast': 20, 'stl': 7.0, 'blk': 5, 'tov': 13, 'pf': None, 'plus_minus': 4.0, 'date_time_processed': '2025-12-05T01:47:55.280701+00:00'}, {'season_id': '22017', 'team_id': 1610612762, 'team_abbreviation': None, 'team_name': None, 'game_id': '0021700702', 'game_date': '2018-01-24', 'matchup': 'UTA @ DET', 'wl': 'W', 'min': None, 'pts': 98, 'fgm': None, 'fga': None, 'fg_pct': 0.396, 'fg3m': None, 'fg3a': None, 'fg3_pct': 0.323, 'ftm': None, 'fta': None, 'ft_pct': 0.75, 'oreb': None, 'dreb': None, 'reb': 44.0, 'ast': 24, 'stl': 11.0, 'blk': 9, 'tov': 14, 'pf': None, 'plus_minus': 3.0, 'date_time_processed': '2025-12-05T01:47:55.280701+00:00'}], count=None)